{% set name = "mkdocs-autorefs" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a86b93abff653521bda71cf3fc5596342b7a23982093915cb74273f67522190f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pdm-backend
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0
    - mkdocs >=1.1
    - markdown >=3.3
    - markupsafe >=2.0.1
    - pymdown-extensions
    # - Markdown >=3.3
    # - Markdown >=3.3
    # - Markdown >=3.3

test:
  imports:
    - mkdocs_autorefs
  commands:
    - pip check
    # - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/mkdocstrings/autorefs
  summary: Automatically link across pages in MkDocs.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
